version: '3.8'

services:
  redis-7000:
    container_name: redis-7000
    image: redis:7.2-alpine
    ports:
      - "7000:7000"
    command: ["redis-server", "--port", "7000", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.10

  redis-7001:
    container_name: redis-7001
    image: redis:7.2-alpine
    ports:
      - "7001:7001"
    command: ["redis-server", "--port", "7001", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.11

  redis-7002:
    container_name: redis-7002
    image: redis:7.2-alpine
    ports:
      - "7002:7002"
    command: ["redis-server", "--port", "7002", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.12

  redis-7003:
    container_name: redis-7003
    image: redis:7.2-alpine
    ports:
      - "7003:7003"
    command: ["redis-server", "--port", "7003", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.13

  redis-7004:
    container_name: redis-7004
    image: redis:7.2-alpine
    ports:
      - "7004:7004"
    command: ["redis-server", "--port", "7004", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.14

  redis-7005:
    container_name: redis-7005
    image: redis:7.2-alpine
    ports:
      - "7005:7005"
    command: ["redis-server", "--port", "7005", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.15

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
